[2018-08-24T16:20:43.252] [INFO] Main Service - Received SIGTERM, going to shutdown server.
[2018-08-24T16:20:43.258] [INFO] Main Service - Server stopped
[2018-08-24T16:20:43.259] [INFO] Main Service - Exited... Buy :)
[2018-08-25T07:00:06.409] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:00:06.473] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:01:20.505] [ERROR] MailSender - Email send was rejected by error: Error: getaddrinfo ENOTFOUND smtp.gmail.com smtp.gmail.com:465
[2018-08-25T07:05:03.155] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:05:03.228] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:07:13.630] [INFO] MailSender - Email was successfully sent to shvajka@gmail.com
[2018-08-25T07:08:17.524] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:08:17.593] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:10:01.747] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:10:01.810] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:12:22.403] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:12:22.469] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:12:57.015] [INFO] MailSender - Email was successfully sent to shvajka@gmail.com
[2018-08-25T07:19:20.169] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:19:20.233] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:19:56.490] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:19:56.552] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:20:51.795] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:20:51.860] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:21:58.673] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:21:58.738] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:23:17.184] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:23:17.247] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:23:40.910] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:23:40.973] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:24:04.627] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:24:04.691] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:24:45.273] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:24:45.340] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:24:56.687] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:24:56.752] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:25:37.652] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:25:37.720] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:26:42.099] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:26:42.164] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:29:30.695] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:29:30.762] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:30:34.017] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:30:34.092] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:30:46.411] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:30:46.481] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:32:05.956] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:32:06.023] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:32:12.774] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:32:12.839] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:32:31.932] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:32:31.996] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:32:42.321] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:32:42.397] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:33:29.419] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:33:29.494] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:34:29.319] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:34:29.392] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:34:51.290] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:34:51.360] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:35:31.549] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:35:31.631] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:36:09.930] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:36:09.997] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:36:37.101] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:36:37.168] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:37:13.034] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:37:13.109] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:42:24.095] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:42:24.162] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:42:29.144] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:42:29.210] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:43:56.057] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:43:56.126] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:44:00.792] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:44:00.863] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:46:32.827] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:46:32.890] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:46:38.661] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:46:38.724] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:50:34.929] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:50:34.995] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:51:20.640] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:51:20.724] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:51:35.325] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:51:35.402] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:52:18.064] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:52:18.128] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:53:13.818] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:53:13.881] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:55:51.023] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:55:51.096] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:56:22.520] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:56:22.585] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:56:34.926] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:56:34.992] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:58:01.961] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:58:02.026] [INFO] Main Service - Succesfully connected to db
[2018-08-25T07:59:32.000] [INFO] Main Service - App listening on port 3000
[2018-08-25T07:59:32.066] [INFO] Main Service - Succesfully connected to db
[2018-08-25T08:41:31.740] [INFO] Main Service - Received SIGTERM, going to shutdown server.
[2018-08-25T08:41:31.753] [INFO] Main Service - Server stopped
[2018-08-25T08:41:31.754] [INFO] Main Service - Exited... Buy :)
[2018-09-15T21:20:04.537] [INFO] Main Service - App listening on port 3000
[2018-09-15T21:20:04.623] [INFO] Main Service - Succesfully connected to db
[2018-09-15T21:25:17.968] [INFO] MailSender - Email was successfully sent to shvajka@gmail.com
[2018-09-15T21:26:09.559] [ERROR] Main Service - Request error  IncomingMessage {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  socket: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      TCP {
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0,
        _consumed: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Array],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Array],
        timeout: [Function: socketOnTimeout],
        data: [Function: bound socketOnData],
        error: [Function: socketOnError],
        close: [Array],
        resume: [Function: onSocketResume],
        pause: [Function: onSocketPause] },
     _eventsCount: 10,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _idleTimeout: 120000,
     _idleNext: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idlePrev: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idleStart: 366766,
     _destroyed: false,
     parser: 
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': [Function: bound onParserExecute],
        _headers: [],
        _url: '',
        _consumed: true,
        socket: [Circular],
        incoming: [Circular],
        outgoing: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: bound parserOnIncoming] },
     on: [Function: socketOnWrap],
     _paused: false,
     _httpMessage: 
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: {},
        [Symbol(outHeadersKey)]: [Object] },
     [Symbol(asyncId)]: 863,
     [Symbol(bytesRead)]: 0,
     [Symbol(asyncId)]: 864,
     [Symbol(triggerAsyncId)]: 863 },
  connection: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      TCP {
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0,
        _consumed: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Array],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Array],
        timeout: [Function: socketOnTimeout],
        data: [Function: bound socketOnData],
        error: [Function: socketOnError],
        close: [Array],
        resume: [Function: onSocketResume],
        pause: [Function: onSocketPause] },
     _eventsCount: 10,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _idleTimeout: 120000,
     _idleNext: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idlePrev: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idleStart: 366766,
     _destroyed: false,
     parser: 
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': [Function: bound onParserExecute],
        _headers: [],
        _url: '',
        _consumed: true,
        socket: [Circular],
        incoming: [Circular],
        outgoing: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: bound parserOnIncoming] },
     on: [Function: socketOnWrap],
     _paused: false,
     _httpMessage: 
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: {},
        [Symbol(outHeadersKey)]: [Object] },
     [Symbol(asyncId)]: 863,
     [Symbol(bytesRead)]: 0,
     [Symbol(asyncId)]: 864,
     [Symbol(triggerAsyncId)]: 863 },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: true,
  headers: 
   { 'content-type': 'application/json',
     'cache-control': 'no-cache',
     'postman-token': '6ce7fece-05fe-4293-86f6-7155b9b3a660',
     'user-agent': 'PostmanRuntime/7.3.0',
     accept: '*/*',
     host: 'localhost:3000',
     'accept-encoding': 'gzip, deflate',
     'content-length': '34',
     connection: 'keep-alive' },
  rawHeaders: 
   [ 'Content-Type',
     'application/json',
     'cache-control',
     'no-cache',
     'Postman-Token',
     '6ce7fece-05fe-4293-86f6-7155b9b3a660',
     'User-Agent',
     'PostmanRuntime/7.3.0',
     'Accept',
     '*/*',
     'Host',
     'localhost:3000',
     'accept-encoding',
     'gzip, deflate',
     'content-length',
     '34',
     'Connection',
     'keep-alive' ],
  trailers: {},
  rawTrailers: [],
  upgrade: false,
  url: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5',
  method: 'POST',
  statusCode: null,
  statusMessage: null,
  client: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      TCP {
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0,
        _consumed: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Array],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Array],
        timeout: [Function: socketOnTimeout],
        data: [Function: bound socketOnData],
        error: [Function: socketOnError],
        close: [Array],
        resume: [Function: onSocketResume],
        pause: [Function: onSocketPause] },
     _eventsCount: 10,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        _pendingResponseData: 0,
        maxHeadersCount: null,
        _connectionKey: '6::::3000',
        [Symbol(asyncId)]: 22 },
     _idleTimeout: 120000,
     _idleNext: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idlePrev: 
      TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: [Object],
        _unrefed: true,
        msecs: 120000,
        nextTick: false },
     _idleStart: 366766,
     _destroyed: false,
     parser: 
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': [Function: bound onParserExecute],
        _headers: [],
        _url: '',
        _consumed: true,
        socket: [Circular],
        incoming: [Circular],
        outgoing: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: bound parserOnIncoming] },
     on: [Function: socketOnWrap],
     _paused: false,
     _httpMessage: 
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: {},
        [Symbol(outHeadersKey)]: [Object] },
     [Symbol(asyncId)]: 863,
     [Symbol(bytesRead)]: 0,
     [Symbol(asyncId)]: 864,
     [Symbol(triggerAsyncId)]: 863 },
  _consuming: true,
  _dumped: false,
  next: [Function: next],
  baseUrl: '',
  originalUrl: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5',
  _parsedUrl: 
   Url {
     protocol: null,
     slashes: null,
     auth: null,
     host: null,
     port: null,
     hostname: null,
     hash: null,
     search: null,
     query: null,
     pathname: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5',
     path: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5',
     href: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5',
     _raw: '/api/v1/action/5b9d4e8b1e85f44b96fd01c5' },
  params: {},
  query: {},
  res: 
   ServerResponse {
     domain: null,
     _events: { finish: [Function: bound resOnFinish] },
     _eventsCount: 1,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: false,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: true,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: false,
     _headerSent: false,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 366766,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 863,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 864,
        [Symbol(triggerAsyncId)]: 863 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 366766,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 863,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 864,
        [Symbol(triggerAsyncId)]: 863 },
     _header: null,
     _onPendingData: [Function: bound updateOutgoingData],
     _sent100: false,
     _expect_continue: false,
     req: [Circular],
     locals: {},
     [Symbol(outHeadersKey)]: { 'x-powered-by': [Array] } },
  body: { password: 'SomePassword123' },
  _body: true,
  length: undefined,
  read: [Function],
  secret: undefined,
  cookies: {},
  signedCookies: {} }
[2018-09-16T13:51:01.065] [INFO] Main Service - App listening on port 3000
[2018-09-16T13:51:01.085] [INFO] Main Service - Succesfully connected to db
[2018-09-16T13:51:45.337] [INFO] Main Service - App listening on port 3000
[2018-09-16T13:51:45.404] [INFO] Main Service - Succesfully connected to db
[2018-09-16T13:52:15.271] [INFO] Main Service - App listening on port 3000
[2018-09-16T13:52:15.334] [INFO] Main Service - Succesfully connected to db
[2018-09-16T13:55:02.166] [INFO] Main Service - App listening on port 3000
[2018-09-16T13:55:02.189] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:00:15.138] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:00:15.195] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:00:56.747] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:00:56.766] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:01:17.134] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:01:17.154] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:01:27.662] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:01:27.683] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:01:31.759] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:01:31.818] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:01:50.900] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:01:50.920] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:01:59.370] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:01:59.389] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:02:10.605] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:02:10.625] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:03:00.924] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:03:00.944] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:03:37.677] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:03:37.696] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:03:53.496] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:03:53.515] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:00.362] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:00.385] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:06.790] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:06.811] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:16.736] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:16.756] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:23.606] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:23.626] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:32.941] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:32.960] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:37.857] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:04:37.876] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:04:40.067] [ERROR] Main Service - Unhandled rejection Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:267:15)
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:83:20
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T14:05:11.615] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:05:11.635] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:05:52.608] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:05:52.628] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:05:57.729] [ERROR] Main Service - Unhandled rejection Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:267:15)
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:84:20
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:39:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T14:06:31.826] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:06:31.846] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:06:42.491] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:06:42.510] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:06:46.367] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:06:46.388] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:06:53.428] [ERROR] Main Service - Unhandled rejection Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:267:15)
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:83:20
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T14:07:04.634] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:07:04.653] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:07:11.731] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:07:11.755] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:07:14.285] [ERROR] Main Service - Unhandled rejection Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/response.js:267:15)
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:83:20
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T14:07:26.819] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:07:26.838] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:16:48.443] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:16:48.467] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:19:34.294] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:19:34.353] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:19:40.284] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:19:40.341] [INFO] Main Service - Succesfully connected to db
[2018-09-16T14:19:50.531] [INFO] Main Service - App listening on port 3000
[2018-09-16T14:19:50.551] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:05:02.112] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:05:02.132] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:09:34.654] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:09:34.673] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:09:40.575] [ERROR] Main Service - Unhandled rejection ReferenceError: next is not defined
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:83:9
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T15:09:54.380] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:09:54.400] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:10:25.751] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:10:25.773] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:10:52.226] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:10:52.284] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:11:55.473] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:11:55.496] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:12:00.106] [ERROR] Main Service - Unhandled rejection ReferenceError: user is not defined
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:78:23
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T15:12:28.121] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:12:28.141] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:12:30.513] [ERROR] Main Service - Unhandled rejection ReferenceError: user is not defined
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:78:23
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-09-16T15:12:45.134] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:12:45.153] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:12:48.752] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:12:59.332] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:12:59.351] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:13:01.397] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:13:22.154] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:13:22.174] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:13:26.711] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:13:26.730] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:13:30.839] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:13:30.859] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:13:51.689] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:13:51.710] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:14:01.149] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:14:32.823] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:14:32.843] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:19:08.815] [ERROR] Main Service - Request error  { ValidationError: User with email of 'shvajka@gmail.com' already exists
    at new ValidationError (/home/dima/Documents/checkersApp/apps/api/src/lib/errorHandler.js:16:15)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:136:23
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 400, name: 'ValidationError', details: undefined }
[2018-09-16T15:21:29.418] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:25:20.792] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:25:20.814] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:25:29.022] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:26:37.344] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:26:37.364] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:26:42.803] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:27:22.094] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:27:22.157] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:27:32.869] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:28:10.135] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:28:10.155] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:28:29.261] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:28:29.283] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:28:33.405] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:79:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:28:55.981] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:28:56.041] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:29:04.360] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:29:04.379] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:29:25.918] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:79:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:30:05.202] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:30:05.221] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:30:09.030] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:30:34.276] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:30:34.295] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:30:38.588] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:81:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:30:54.049] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:30:54.069] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:30:58.203] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:81:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:31:22.279] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:31:22.303] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:31:24.353] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:81:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:31:32.208] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:31:32.235] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:31:47.464] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:31:47.483] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:31:50.775] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:81:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:33:53.274] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:33:53.293] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:33:58.045] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:35:36.192] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:35:36.257] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:35:38.277] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:19
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:37:12.198] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:37:12.217] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:37:22.019] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:37:22.042] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:37:35.661] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:37:35.685] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:37:37.924] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:37:37.951] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:37:40.603] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:23
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:38:11.905] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:38:11.924] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:38:15.658] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:81:23
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:40:30.025] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:40:30.046] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:40:32.133] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:40:32.154] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:40:37.648] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:40:37.669] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:40:39.859] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:40:39.880] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:40:44.553] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:82:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:40:59.552] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:40:59.572] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:41:04.043] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:82:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:41:40.923] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:41:40.947] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:41:45.764] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:82:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:43:17.304] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:43:17.324] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:43:23.823] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:84:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:43:48.901] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:43:48.920] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:43:54.927] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:85:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:38:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:44:59.487] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:44:59.545] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:45:05.944] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:85:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:39:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:45:35.471] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:45:35.491] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:45:48.422] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:45:48.443] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:45:54.443] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:87:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:41:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:46:18.034] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:46:18.054] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:46:22.611] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:46:22.631] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:46:31.535] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:88:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:42:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T15:57:57.138] [INFO] Main Service - App listening on port 3000
[2018-09-16T15:57:57.157] [INFO] Main Service - Succesfully connected to db
[2018-09-16T15:58:02.653] [INFO] Main Service - Received SIGTERM, going to shutdown server.
[2018-09-16T15:58:02.659] [INFO] Main Service - Server stopped
[2018-09-16T15:58:02.659] [INFO] Main Service - Exited... Buy :)
[2018-09-16T16:38:11.422] [INFO] Main Service - App listening on port 3000
[2018-09-16T16:38:11.449] [INFO] Main Service - Succesfully connected to db
[2018-09-16T16:38:19.146] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at /home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:88:27
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:42:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T16:39:05.074] [INFO] Main Service - App listening on port 3000
[2018-09-16T16:39:05.093] [INFO] Main Service - Succesfully connected to db
[2018-09-16T16:40:59.725] [INFO] Main Service - App listening on port 3000
[2018-09-16T16:40:59.745] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:22:27.900] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:22:27.919] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:28:57.440] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:28:57.468] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:29:37.850] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:29:37.871] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:30:57.748] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:30:57.772] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:41:30.180] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:41:30.244] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:43:12.971] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:43:12.992] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:43:25.083] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:43:25.103] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:43:44.123] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:43:44.142] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:43:48.182] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at _passport2.default.authenticate (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:86:23)
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:42:13)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T17:44:38.898] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:44:38.917] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:45:55.588] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:45:55.607] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:46:27.528] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:46:27.548] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:47:00.301] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:47:00.323] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:47:43.515] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:47:43.535] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:48:02.923] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:48:02.942] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:48:09.952] [ERROR] Main Service - Unhandled rejection ReferenceError: args is not defined
    at _passport2.default.authenticate (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:82:25)
    at Strategy.strategy.success (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:214:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:83:10)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:35:17)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T17:48:24.990] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:48:25.010] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:48:31.414] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:48:31.433] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:48:33.237] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: [object Object]
    at _passport2.default.authenticate (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:23)
    at Strategy.strategy.success (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:214:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:83:10)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:35:17)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T17:49:00.917] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:49:00.936] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:49:28.243] [ERROR] Main Service - Unhandled rejection { UnauthorizedError: Wrong email or password
    at _passport2.default.authenticate (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:80:23)
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:37:17)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T17:50:13.202] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:50:13.222] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:50:19.638] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:50:19.657] [INFO] Main Service - Succesfully connected to db
[2018-09-16T17:59:52.592] [INFO] Main Service - App listening on port 3000
[2018-09-16T17:59:52.611] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:00:45.362] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:00:45.382] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:03:27.802] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:03:27.821] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:05:07.776] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:05:07.795] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:05:37.676] [ERROR] Main Service - Request error  { UnauthorizedError: Wrong email or password
    at _passport2.default.authenticate (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:83:24)
    at Strategy.strategy.error (/home/dima/Documents/checkersApp/apps/api/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/home/dima/Documents/checkersApp/apps/api/node_modules/passport-local/lib/strategy.js:81:28)
    at Strategy.<anonymous> (/home/dima/Documents/checkersApp/apps/api/src/lib/passport.js:26:17)
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous> status: 401, name: 'UnauthorizedError' }
[2018-09-16T18:05:50.432] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:05:50.452] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:06:41.378] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:06:41.398] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:23:40.846] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:23:40.913] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:24:12.476] [ERROR] Main Service - Request error  { ValidationError: Validation failed
    at new ValidationError (/home/dima/Documents/checkersApp/apps/api/src/lib/errorHandler.js:16:15)
    at _nodeValidator2.default.run (/home/dima/Documents/checkersApp/apps/api/src/lib/validator.js:10:31)
    at Object.run (/home/dima/Documents/checkersApp/apps/api/node_modules/node-validator/lib/validator.js:40:3)
    at Object._nodeValidator2.default.validate (/home/dima/Documents/checkersApp/apps/api/src/lib/validator.js:7:15)
    at UserService._validateUserCredentials (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:317:19)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:93:18
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionCreate (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:91:42)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:112:3)
  status: 400,
  name: 'ValidationError',
  details: 
   [ { parameter: 'email',
       value: undefined,
       message: 'Required value.' },
     { parameter: 'password',
       value: undefined,
       message: 'Required value.' } ] }
[2018-09-16T18:28:30.538] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:28:30.556] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:29:46.296] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:29:46.316] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:30:03.350] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:30:03.374] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:31:53.016] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:31:53.078] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:31:54.422] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:123:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:32:00.803] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:123:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:32:26.453] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:123:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:32:27.352] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:123:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:33:09.241] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:33:09.299] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:33:12.907] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:126:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:33:24.361] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:33:24.420] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:33:27.290] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:33:27.349] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:33:30.222] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:126:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:33:53.959] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:33:53.979] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:34:04.056] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:34:04.117] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:34:36.640] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:34:36.702] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:34:40.495] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:106:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:126:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:35:02.116] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:35:02.175] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:35:04.410] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:107:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:128:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:35:48.558] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:35:48.577] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:36:11.577] [INFO] Main Service - App listening on port 3000
[2018-09-16T18:36:11.596] [INFO] Main Service - Succesfully connected to db
[2018-09-16T18:36:19.670] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:107:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:128:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
[2018-09-16T18:37:10.179] [ERROR] Main Service - Request error  Error: payload is required
    at Object.module.exports [as sign] (/home/dima/Documents/checkersApp/apps/api/node_modules/jsonwebtoken/sign.js:105:20)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:107:31
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/dima/Documents/checkersApp/apps/api/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at UserService._sessionRenew (/home/dima/Documents/checkersApp/apps/api/src/services/user.js:103:41)
    at Layer.handle [as handle_request] (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dima/Documents/checkersApp/apps/api/node_modules/express/lib/router/route.js:137:13)
    at /home/dima/Documents/checkersApp/apps/api/src/services/user.js:128:13
    at Generator.next (<anonymous>)
    at step (/home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dima/Documents/checkersApp/apps/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
